django_netjsonconfig/static/django-netjsonconfig/css/lib/advanced-mode.css
fixed fullscreen cover issue #49  @nemesisdesign
=> [UI] fixed fullscreen covering preview issue

.travis.yml, django_netjsonconfig/base/admin.py, django_netjsonconfig/static/django-netjsonconfig/css/admin.css, django_netjsonconfig/static/django-netjsonconfig/js/uuid.js, django_netjsonconfig/tests/test_admin.py, django_netjsonconfig/utils.py, requirements.txt
=> [django] Upgraded to django 1.11

.travis.yml, django_netjsonconfig/base/admin.py, django_netjsonconfig/base/config.py, django_netjsonconfig/base/template.py, django_netjsonconfig/base/vpn.py, django_netjsonconfig/controller/urls.py, django_netjsonconfig/urls.py, django_netjsonconfig/views.py, django_netjsonconfig/widgets.py, requirements.txt, tests/settings.py, tests/urls.py
Temporarily install django-x509 from master before new release
=> [travis] Added django 2.0 to tests

README.rst
There where several small errors in the documentation as well as some important missing information.
In addition to correcting these, I have also added a link to a working minimal example project. I expect this project to need moving to this organization before this PR is accepted.
=> Documentation for extending django-netjsonconfig

django_netjsonconfig/base/admin.py, django_netjsonconfig/templates/admin/django_netjsonconfig/change_form.html, django_netjsonconfig/tests/test_admin.py
=> [admin] Added an error if a device has no config. and a download is attempted

django_netjsonconfig/widgets.py
Minor change, but opened the PR to test build.
=> [JsonSchemaWidget] Added renderer argument (django 2.1)

.travis.yml, requirements-test.txt, runflake8, setup.cfg
Updated requirements-text.txt and moved settings related to flake8 to setup.cfg.
GCI Task: https://codein.withgoogle.com/dashboard/task-instances/4898507346411520/
=> [qa] Cleanup flake8 settings

.travis.yml, runcheckmigration
=> [qa] Added run check migration

django_netjsonconfig/base/vpn.py, django_netjsonconfig/migrations/0039_vpn_format_dh.py, django_netjsonconfig/tests/test_vpn.py
=> [vpn] Fixed DH params in preview and download configuration #107

django_netjsonconfig/api/generics.py, django_netjsonconfig/api/serializers.py, django_netjsonconfig/api/urls.py, django_netjsonconfig/api/views.py, django_netjsonconfig/tests/test_admin.py, django_netjsonconfig/urls.py, django_netjsonconfig/utils.py, requirements.txt, tests/settings.py, tests/urls.py
Added an API end point which will be use for
the serialization of templates to json format
for imports. Taking into account the
fact that a template can be generic or
a VPN-client.
Fixes #96
=> [API] Added API for template serialization #96

.travis.yml, django_netjsonconfig/base/admin.py, requirements.txt
=> [requirements] Django2.2 #108

django_netjsonconfig/controller/generics.py, django_netjsonconfig/tests/test_controller.py
Testing my improvements of #139 on travis.
=> Fix issue 64

django_netjsonconfig/base/admin.py, django_netjsonconfig/base/template.py, django_netjsonconfig/tests/test_admin.py, django_netjsonconfig/tests/test_template.py
=> Clone templates

.travis.yml, runcheckmigration, runisort
Replace old qa checks with openwisp-utils-qa-checks (related to openwisp/openwisp-utils#63 for this repo)
=> [enhancement] Replace with openwisp-utils-qa-checks

django_netjsonconfig/base/admin.py, django_netjsonconfig/base/device.py, django_netjsonconfig/base/tag.py, django_netjsonconfig/base/vpn.py, django_netjsonconfig/migrations/0001_initial.py, django_netjsonconfig/migrations/0024_add_device_model.py, django_netjsonconfig/migrations/0038_vpn_key.py, django_netjsonconfig/static/django-netjsonconfig/js/uuid.js, django_netjsonconfig/tests/test_admin.py, django_netjsonconfig/utils.py, requirements-test.txt, requirements.txt, tests/settings.py
Removed the logics which were duplicated
in the others modules and redefined it here to enable reusability and ease debugging.
Related to openwisp/openwisp-utils#40
=> [django] Generalize uuid/key logic openwisp/openwisp-utils#40

CHANGES.rst, django_netjsonconfig/__init__.py
=> 0.10.0 release

.gitignore, django_netjsonconfig/static/django-netjsonconfig/js/switcher.js
Made Configuration visible when template type is changed from VPN
=> [bug] Configuration stays hidden when template is changed from VPN

django_netjsonconfig/migrations/0004_config_allow_blank.py, django_netjsonconfig/migrations/0010_basemodel_reorganization.py, django_netjsonconfig/migrations/0011_template_config_blank.py, django_netjsonconfig/migrations/0037_config_context.py, django_netjsonconfig/tests/test_admin.py
=> [tests] Fixed failing test after switch to jsonfield #152

django_netjsonconfig/static/django-netjsonconfig/js/unsaved_changes.js
Switched onload to ondomready, seems the calculation of initial values
is inconsistent when using onload.
Fixes #149
=> [js] Fixed unsaved changes #149

django_netjsonconfig/tests/test_admin.py
Hopefully, this might help somebody avoid unnecessary trouble, I spent 4 hrs figuring out what went wrong. :pensive:
Closes #150
=> [enhancement] Remove unnecessary tracebacks from being displayed

django_netjsonconfig/base/base.py, django_netjsonconfig/tests/test_config.py, django_netjsonconfig/tests/test_controller.py, django_netjsonconfig/tests/test_template.py
Improved PR #160 to handle duplicated files.
=> [models] Handle duplicated files

django_netjsonconfig/base/admin.py, django_netjsonconfig/base/config.py, django_netjsonconfig/tests/test_admin.py
@okraits found out this bug and fixed it.
=> [bugfix] Fixed broken preview when using hardware_id context var

django_netjsonconfig/base/admin.py
Hide context field into advanced options
=> [admin] Hide context field into advanced options

django_netjsonconfig/base/admin.py, django_netjsonconfig/tests/test_admin.py
=> [admin] 404 on Device change page raises 500 internal server error

django_netjsonconfig/controller/generics.py, django_netjsonconfig/signals.py, django_netjsonconfig/tests/test_controller.py
Emit signals after checksum and config download.
Closes #174
=> [controller] Emit signals after checksum and config download #174
